-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE CLIENTE (
ID_CLIENTE Texto(1) PRIMARY KEY,
NOME VARCHAR(60)
)

CREATE TABLE PEDIDO (
ID_PEDIDO Texto(1) PRIMARY KEY,
QUANTIDADE VARCHAR(60),
ID_CLIENTE Texto(1),
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
)

CREATE TABLE PRODUTOS+ESTOQUES (
ID_PRODUTOS VARCHAR(100),
NOME VARCHAR(100),
ID_ESTOQUES VARCHAR(100),
VALOR Texto(1)VARCHAR(100),
PRIMARY KEY(ID_PRODUTOS,ID_ESTOQUES)
)

CREATE TABLE FORNACEDORES (
ID_FORNECEDORES IDE_FORNECEDORES PRIMARY KEY,
RAZAO_SOCIAL Texto(1)
)

CREATE TABLE PRODUTOS (
ID_PRODUTOS Texto(1) PRIMARY KEY,
NOME Texto(1)
)

CREATE TABLE ITEM_PRODUTO (
ID_PRODUTOS INT ,
ID_FORNECEDORES INT ,
ID_ITEM INT AUTO_INCREMENT PRIMARY  KEY PRIMARY KEY,
QUANTIDADE INT
)

